### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by mike10004** [skela/linkedin-java#4]
Would you care to specify a license under which others can use this library? http://choosealicense.com/

**Comment by mike10004** [comment]
Note: I see that some files do have license headers, e.g. [Company.java](https://github.com/skela/linkedin-java/blob/1028e62cd83cdf2d594cf16335b33ef07e1ade3e/Main/src/org/linkedin/schema/Company.java)  and [Person.java](https://github.com/skela/linkedin-java/blob/1028e62cd83cdf2d594cf16335b33ef07e1ade3e/Main/src/org/linkedin/schema/Person.java) are Apache-licensed. However, some files do not specify any license, e.g. [LinkedIn.java](https://github.com/skela/linkedin-java/blob/1028e62cd83cdf2d594cf16335b33ef07e1ade3e/Main/src/org/linkedin/LinkedIn.java). Putting a `LICENSE` file in the top directory would resolve the ambiguity.

**Comment by skela** [comment]
Ah, sorry @mike10004 , totally missed the notifications for this. I'll sort this out asap.

**Comment by skela** [comment]
Right, thats added now, let me know if there's a problem with it.
