### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by arranzropablo** [skela/linkedin-java#5]
Hello,
I've tried to use this library which looked very nice for my purpose and I realized it's no longer working because LinkedIn API have changed, so I've developed my own functionality.

Are you planning on making it work again? I could help!

Regards.

**Comment by skela** [comment]
Hi, I probably wont make it work again unless I need to use it for something in one of my projects.
Feel free to provide pull requests and I will merge them in if you want, I'm happy to accept help if you want to provide it ;)
